src/EventPage/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventPage.Data.Migrations;
using EventPage.Models;
using Microsoft.AspNetCore.Authorization;

namespace EventPage.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AgendaController : Controller
    {
        private readonly DataDbContext _context;

        public AgendaController(DataDbContext context)
        {
            _context = context;    
        }

        // GET: Agenda
        public async Task<IActionResult> Index()
        {
            return View(await _context.Agenda.ToListAsync());
        }

        // GET: Agenda/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agenda = await _context.Agenda.SingleOrDefaultAsync(m => m.AgendaID == id);
            if (agenda == null)
            {
                return NotFound();
            }

            return View(agenda);
        }

        // GET: Agenda/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Agenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AgendaID,Date,Name")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                _context.Add(agenda);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(agenda);
        }

        // GET: Agenda/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agenda = await _context.Agenda.SingleOrDefaultAsync(m => m.AgendaID == id);
            if (agenda == null)
            {
                return NotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AgendaID,Date,Name")] Agenda agenda)
        {
            if (id != agenda.AgendaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(agenda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AgendaExists(agenda.AgendaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(agenda);
        }

        // GET: Agenda/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agenda = await _context.Agenda.SingleOrDefaultAsync(m => m.AgendaID == id);
            if (agenda == null)
            {
                return NotFound();
            }

            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var agenda = await _context.Agenda.SingleOrDefaultAsync(m => m.AgendaID == id);
            _context.Agenda.Remove(agenda);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AgendaExists(int id)
        {
            return _context.Agenda.Any(e => e.AgendaID == id);
        }
    }
}

src/EventPage/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventPage.Data.Migrations;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using static EventPage.Enums.FileTypes;
using EventPage.Helpers.ControllersHelpers;
using Microsoft.AspNetCore.Authorization;

namespace EventPage.Models
{
    [Authorize(Roles = "Administrator")]
    public class PeopleController : Controller
    {
        private readonly DataDbContext _context;
        private IHostingEnvironment _hostEnv;

        public PeopleController(DataDbContext context, IHostingEnvironment appEnv)
        {
            _context = context;
            _hostEnv = appEnv;
        }

    // GET: People
    public async Task<IActionResult> Index()
        {
            return View(await _context.Person.ToListAsync());
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.SingleOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonID,About,Forname,ImagePath,Organizer,PresentationSubject,Surname")] Person person, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = ImageUploader.ImageUpload(_hostEnv, file, "upload", FileType.Images);
                    if (path != null)
                        person.ImagePath = path;
                }

                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.SingleOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonID,About,Forname,ImagePath,Organizer,PresentationSubject,Surname")] Person person, IFormFile file)
        {
            if (id != person.PersonID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = ImageUploader.ImageUpload(_hostEnv, file, "upload", FileType.Images);
                    if (path != null)
                        person.ImagePath = path;
                }

                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.PersonID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.SingleOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Person.SingleOrDefaultAsync(m => m.PersonID == id);
            _context.Person.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PersonExists(int id)
        {
            return _context.Person.Any(e => e.PersonID == id);
        }
    }
}

src/EventPage/Controllers/RafflesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventPage.Data.Migrations;
using EventPage.Models;
using Microsoft.AspNetCore.Authorization;

namespace EventPage.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RafflesController : Controller
    {
        private readonly DataDbContext _context;

        public RafflesController(DataDbContext context)
        {
            _context = context;    
        }

        // GET: Raffles
        public async Task<IActionResult> Index()
        {
            var dataDbContext = _context.Raffle.Include(r => r.Reward).Include(r => r.Winner);
            return View(await dataDbContext.ToListAsync());
        }

        // GET: Raffles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var raffle = await _context.Raffle.SingleOrDefaultAsync(m => m.RaffleID == id);
            if (raffle == null)
            {
                return NotFound();
            }

            return View(raffle);
        }

        // GET: Raffles/Create
        public IActionResult Create()
        {
            ViewData["RewardID"] = new SelectList(_context.Rewards, "RewardsID", "Name");
            ViewData["WinnerID"] = new SelectList(_context.SurveyUser, "SurveyUserID", "Email");
            return View();
        }

        // POST: Raffles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RaffleID,RewardID,WinnerID")] Raffle raffle)
        {
            if (ModelState.IsValid)
            {
                _context.Add(raffle);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["RewardID"] = new SelectList(_context.Rewards, "RewardsID", "Name", raffle.RewardID);
            ViewData["WinnerID"] = new SelectList(_context.SurveyUser, "SurveyUserID", "Email", raffle.WinnerID);
            return View(raffle);
        }

        // GET: Raffles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var raffle = await _context.Raffle.SingleOrDefaultAsync(m => m.RaffleID == id);
            if (raffle == null)
            {
                return NotFound();
            }
            ViewData["RewardID"] = new SelectList(_context.Rewards, "RewardsID", "Name", raffle.RewardID);
            ViewData["WinnerID"] = new SelectList(_context.SurveyUser, "SurveyUserID", "Email", raffle.WinnerID);
            return View(raffle);
        }

        // POST: Raffles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RaffleID,RewardID,WinnerID")] Raffle raffle)
        {
            if (id != raffle.RaffleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(raffle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaffleExists(raffle.RaffleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["RewardID"] = new SelectList(_context.Rewards, "RewardsID", "Name", raffle.RewardID);
            ViewData["WinnerID"] = new SelectList(_context.SurveyUser, "SurveyUserID", "Email", raffle.WinnerID);
            return View(raffle);
        }

        // GET: Raffles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var raffle = await _context.Raffle.SingleOrDefaultAsync(m => m.RaffleID == id);
            if (raffle == null)
            {
                return NotFound();
            }

            return View(raffle);
        }

        // POST: Raffles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var raffle = await _context.Raffle.SingleOrDefaultAsync(m => m.RaffleID == id);
            _context.Raffle.Remove(raffle);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool RaffleExists(int id)
        {
            return _context.Raffle.Any(e => e.RaffleID == id);
        }
    }
}

src/EventPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventPage</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse pr-5 pl-5">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand nav-link" asp-area="" asp-controller="Home" asp-action="Index">Pokochaj UG</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav mr-auto">
                @{ if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Partnerzy
                            </a>
                            <div class="dropdown-menu  bg-inverse" aria-labelledby="navbarDropdownMenuLink2">
                                <a class="nav-item nav-link" asp-area="" asp-controller="Partners" asp-action="Index">Partnerzy</a>
                                <a class="nav-item nav-link" asp-area="" asp-controller="PartnerGroups" asp-action="Index">Podgroupy</a>
                                <a class="nav-item nav-link" asp-area="" asp-controller="PartnerMainGroups" asp-action="Index">Grupy</a>
                            </div>
                        </div>
                        <a class="nav-item nav-link" asp-area="" asp-controller="People" asp-action="Index">Ludzie</a>
                        <a class="nav-item nav-link" asp-area="" asp-controller="Agenda" asp-action="Index">Agenda</a>
                        <a class="nav-item nav-link" asp-area="" asp-controller="EventParts" asp-action="Index">Prelekcje</a>
                        <a class="nav-item nav-link" asp-area="" asp-controller="Raffles" asp-action="Index">Losowania</a>
                        <a class="nav-item nav-link" asp-area="" asp-controller="Rewards" asp-action="Index">Nagrody</a>
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ankiety
                            </a>
                            <div class="dropdown-menu  bg-inverse" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-item nav-link" asp-area="" asp-controller="SurveyUsers" asp-action="Index">Użytkownicy</a>
                                <a class="nav-item nav-link" asp-area="" asp-controller="SurveyResults" asp-action="Index">Wypełnione</a>
                            </div>
                        </div>
                            <a class="nav-item nav-link" asp-area="" asp-controller="RaffleAPI" asp-action="Index">Nowe losowanie</a>
                            }
                            }
                            @await RenderSectionAsync("navlinks", required: false)
</div>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-right">&copy; 2017- Damian Żołądek</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="~/lib/gsap/src/minified/TweenMax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDX1olzfBykCCHfN1edq_2VAF9VH14aYqM"></script>
    <script src="~/js/raffle.js"></script>

    @RenderSection("scripts", required: false)
</body>

</html>

src/EventPage/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventPage</title>
    <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
    <link rel="stylesheet" href="~/css/loader.css" />
    <link rel="stylesheet" href="~/lib/SpinKit/css/spinkit.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/siteUser.css" />
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse pr-5 pl-5">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand nav-link" href="#intro">Pokochaj UG</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @await RenderSectionAsync("navlinks", required: false)
            </ul>
             @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
    <div class="body-content">
        <div id="loader-wrapper">
            <div id="loader"></div>

            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>

        </div>
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2017 - Damian Żołądek</p>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="~/lib/gsap/src/minified/TweenMax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDX1olzfBykCCHfN1edq_2VAF9VH14aYqM"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/lib/iframe-resizer/js/iframeResizer.min.js"></script>
    <script src="~/js/loader.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>